### ISSUE TITLE
How to handle numpy array without to use loadTensor?

### ISSUE THREAD

**Issue by marlon-shiftone** [BGT-M/spartan2-tutorials#8]
Hello,

I have seen the tutorial, in which you load a file by using loadTensor class. How can I simply handle numpy array without saving it and loading as a file?

Thanks

**Comment by HQJo** [comment]
Thanks for your attention!

About your question, `loadTensor()` return a `TensorData` object, which can be constructed from a `pandas.DataFrame` object directly. 

For example,
```python
import numpy as np
import pandas as pd
from spartan.tensor import TensorData

arr = np.load('your_array.npy')
df = pd.DataFrame(arr)
tensor = TensorData(df)
```

**Comment by marlon-shiftone** [comment]
Thanks!
